# Generated by Django 3.1.3 on 2020-12-01 13:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201201_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 1, 13, 25, 26, 158701, tzinfo=utc)),
        ),
    ]
