# Generated by Django 3.1.3 on 2021-02-22 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0021_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.ManyToManyField(related_name='save_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
